version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mypayloadfun"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d4g2x07af9dc"
s3_prefix = "mypayloadfun"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=139182442186.dkr.ecr.us-west-2.amazonaws.com/mycloudformationef03a238/helloworldfunction19d43fc4repo"]
